/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/home/zyc/rust_projects/BYYL/bison-3.7.91-build"
#define EXEC_PREFIX "/home/zyc/rust_projects/BYYL/bison-3.7.91-build"
#define BINDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/bin"
#define SBINDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/sbin"
#define LIBEXECDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/libexec"
#define DATAROOTDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share"
#define DATADIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share"
#define SYSCONFDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/etc"
#define SHAREDSTATEDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/com"
#define LOCALSTATEDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/var"
#define RUNSTATEDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/var/run"
#define INCLUDEDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/doc/bison"
#define INFODIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/info"
#define HTMLDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/doc/bison"
#define DVIDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/doc/bison"
#define PDFDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/doc/bison"
#define PSDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/doc/bison"
#define LIBDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/lib"
#define LISPDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/emacs/site-lisp"
#define LOCALEDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/locale"
#define MANDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/man"
#define PKGDATADIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/share/bison"
#define PKGINCLUDEDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/include/bison"
#define PKGLIBDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/lib/bison"
#define PKGLIBEXECDIR "/home/zyc/rust_projects/BYYL/bison-3.7.91-build/libexec/bison"
